version: "3.8"

services:
  ratelimiter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8550:8080" # HTTP
      - "9090:9090" # gRPC
    command:
      - "--redis-addr=redis:6379"
      - "--http-addr=:8080"
      - "--grpc-addr=:9090"
    environment:
      - RATE_LIMIT=${RATE_LIMIT:-1} # Only 2 requests if not set
      - RATE_WINDOW=${RATE_WINDOW:-2s} # Per 5 seconds if not set
      - BURST_SIZE=${BURST_SIZE:-3} # Allow burst of 3 if not set
      - DEBUG=${DEBUG:-true} # Enable debug logging if not set
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - drl-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - drl-network

  # loadtest:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.test
  #   volumes:
  #     - ./api:/app/api:ro  # Mount proto files for gRPC testing
  #   depends_on:
  #     - ratelimiter
  #   networks:
  #     - drl-network

volumes:
  redis-data:

networks:
  drl-network:
    driver: bridge
